# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db14903f6732b590b9f11322bc4786ec72cb52c11d78793ec818228cfc99204da5ff20cf30b359d94f84a8e06a9644ed226060a0d211314866ef2b029ef4b1e4

test:
  secret_key_base: bda21948c8081d9c81e8e146f6fccee19399796ce113bd7452e04becf2bba175b55d31cf0b57403a22fbeccacb1ca7d8abe4efcd4c075aba60cc8a4aa47c321a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
